"""One more thing

Revision ID: ff4c44e62986
Revises: 42989ed2ac38
Create Date: 2025-05-13 13:40:59.804381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4c44e62986'
down_revision: Union[str, None] = '42989ed2ac38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('P', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('Q', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('R', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('S', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('T', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('P_interval', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('QRS', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('T_interval', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('sample_id', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('comments', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('patient', 'last_checked_patient')
    op.drop_column('patient', 'x_coord')
    op.drop_column('patient', 'current_patient')
    op.drop_column('patient', 'verdict')
    op.drop_column('patient', 'comments_to_parameter')
    op.drop_column('patient', 'parameter')
    op.add_column('user', sa.Column('last_checked_patient', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('current_patient', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_patient')
    op.drop_column('user', 'last_checked_patient')
    op.add_column('patient', sa.Column('parameter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('comments_to_parameter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('verdict', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('current_patient', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('x_coord', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patient', sa.Column('last_checked_patient', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('patient', 'time_created')
    op.drop_column('patient', 'comments')
    op.drop_column('patient', 'sample_id')
    op.drop_column('patient', 'T_interval')
    op.drop_column('patient', 'QRS')
    op.drop_column('patient', 'P_interval')
    op.drop_column('patient', 'T')
    op.drop_column('patient', 'S')
    op.drop_column('patient', 'R')
    op.drop_column('patient', 'Q')
    op.drop_column('patient', 'P')
    # ### end Alembic commands ###
