services:
  #Nginx service
  #  web:
  #    container_name: web
  #    image: nginx:alpine
  #    depends_on:
  #      - auth
  #      - user_meta
  #      - ecg
  #    ports:
  #      - "8082:80"
  #    volumes:
  #      - ./nginx_conf/conf.d:/etc/nginx/conf.d
  #    networks:
  #      - mup

  # PostgreSQL service
  psgr:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_NAME}$
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mup

  # Mongo Service
  mongo:
    image: mongo:6
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - mup

  # Authentication service
  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432/markecg$
    depends_on:
      - psgr
    ports:
      - "8000:8000"
    links:
      - "psgr:db"
    networks:
      - mup

  # Ecg managing service
  ecg:
    build:
      context: .
      dockerfile: services/ecg/Dockerfile
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=ecg
    depends_on:
      - mongo
    links:
      - "psgr:db"
    ports:
      - "8001:8001"
    networks:
      - mup

  # User metadata service
  user_meta:
    build:
      context: .
      dockerfile: services/user_meta/Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432/markecg$
    depends_on:
      - psgr
    ports:
      - "8002:8002"
    links:
      - "psgr:db"
    networks:
      - mup

# Volumes
volumes:
  pgdata:
  mongodata:

# Networks
networks:
  mup:
    driver: bridge