services:
  psgr:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: markecg
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mup

  mongo:
    image: mongo:6
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - mup

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@localhost:5432/markecg"
    depends_on:
      - psgr
    ports:
      - "8000:8000"
    links:
      - "psgr:db"
    networks:
      - mup

  ecg:
    build:
      context: .
      dockerfile: services/ecg/Dockerfile
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      DB_NAME: "ecg"
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    networks:
      - mup

  user_meta:
    build:
      context: .
      dockerfile: services/user_meta/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@localhost:5432/markecg"
    depends_on:
      - psgr
    ports:
      - "8002:8002"
    networks:
      - mup

volumes:
  pgdata:
  mongodata:

networks:
  mup:
    driver: bridge